Implement equals and hashCode on WrappedComponent
KyoriPowered/adventure-platform-fabric pull request #163
Opened 2024-10-10 17:59 UTC by jpenilla

fixes #162

2024-10-10 19:34 UTC, kashike requested changes

2024-10-10 19:34 UTC, kashike commented on mod-shared/src/main/java/net/kyori/adventure/platform/modcommon/impl/WrappedComponent.java
> +    if (obj instanceof WrappedComponent wrappedComponent) {
```suggestion
    if (obj instanceof final WrappedComponent wrappedComponent) {
```

2024-10-12 08:58 UTC, kashike approved these changes

2024-10-12 23:24 UTC, zml2008 commented
Should MC's components' equals() be modified to unwrap WrappedComponnents before comparing?

Otherwise `wrapped.equals(native)` will produce a different result than `native.equals(wrapped)` which is not very fun and cool

2024-10-18 04:58 UTC, zml2008 commented
I think this is ready to merge, it should be backported to the 5.x series as well though I think since I expect 1.21.1 will live a relatively long life.

2024-10-18 04:58 UTC, zml2008 approved these changes

2024-10-18 05:04 UTC, zml2008 commented
I've set up `mc/1.21.1` for that backport, I'll do it unless you have the free time.

2024-10-18 05:08 UTC, merged